<?php
error_reporting(0);
ini_set('display_errors', 0);
mysqli_report(MYSQLI_REPORT_OFF);

if (session_status() === PHP_SESSION_NONE) session_start();

// ===== GUARD: must be logged in =====
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'student') {
    header("Location: slogin.php");
    exit;
}

// ===== DB CONNECTION =====
$conn = new mysqli("127.0.0.1", "root", "", "gcs_db");
$sid  = $conn->real_escape_string($_SESSION['user_id']);

// ===== LOAD STUDENT DATA =====
$studentRes = $conn->query("SELECT * FROM students WHERE student_id='$sid' LIMIT 1");
$student    = $studentRes->fetch_assoc();

$profileRes = $conn->query("SELECT profile_image FROM student_profiles WHERE student_id='$sid' LIMIT 1");
$profile    = $profileRes->fetch_assoc();

$fullName   = htmlspecialchars(($student['first_name'] ?? '') . ' ' . ($student['last_name'] ?? ''));
$email      = htmlspecialchars($student['email'] ?? '');
$profileImg = !empty($profile['profile_image'])
              ? htmlspecialchars($profile['profile_image'])
              : 'https://ui-avatars.com/api/?name=' . urlencode($fullName) . '&background=113f67&color=fff';
?>
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>UNITYCARE | Session Reports</title>

<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="logout.css">

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">

<!-- EXPORT LIB -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
</head>

<body class="body">

<!-- SIDEBAR -->
<aside class="sidebar">
  <div class="sidebar-logoBar">
    <div class="sidebar-logo">
      <img src="logo.png" alt="logo">
      <span class="sidebar-logoText">UNITYCARE</span>
    </div>

    <div class="sidebar-settings">
      <button class="sidebar-settingsButton" onclick="toggleSettingsMenu(event)">
        <i class="fa fa-gear"></i>
      </button>

      <div class="sidebar-settingsDropdown" id="settingsDropdown">
        <a href="sprofile.php"><i class="fa fa-user"></i> Profile</a>
        <a href="shistory.php"><i class="fa fa-clock"></i> Session History</a>
        <button onclick="toggleTheme()"><i class="fa fa-moon"></i> Theme</button>
        <button onclick="logout()"><i class="fa fa-right-from-bracket"></i> Logout</button>
      </div>
    </div>
  </div>

  <nav class="sidebar-menu">
    <a href="dashboard.php"><i class="fa fa-th-large"></i> Dashboard</a>

    <p class="sidebar-title">SERVICES</p>
    <a href="sappointment.php"><i class="fa fa-calendar"></i> Book Appointment</a>
    <a href="sconcerns.php"><i class="fa fa-headset"></i> Submit Concern</a>
    <a href="swellness.php"><i class="fa fa-heart"></i> Wellness Check</a>
    <a href="sreferral.php"><i class="fa fa-route"></i> Referral</a>

    <p class="sidebar-title">UPDATES</p>
    <a href="sannouncements.php"><i class="fa fa-bullhorn"></i> Announcements</a>

    <p class="sidebar-title">RECORDS</p>
    <a href="sreports.php" class="active"><i class="fa fa-ticket"></i> Reports</a>

    <p class="sidebar-title">SYSTEM</p>
    <a href="sfeedback.php"><i class="fa fa-comment"></i> Session Feedback</a>
  </nav>
</aside>

<!-- TOPBAR -->
<header class="topbar">

  <div class="topbar-left">
    <h2>Reports</h2>
  </div>

  <div class="topbar-right">
    <div class="topbar-user">
      <img src="<?= $profileImg ?>" alt="user"
           onerror="this.src='https://ui-avatars.com/api/?name=<?= urlencode($fullName) ?>&background=113f67&color=fff'">
      <div>
        <strong><?= $fullName ?></strong>
        <p><?= $email ?></p>
      </div>
    </div>
  </div>

</header>

<!-- MAIN -->
<main class="sReports-main">

  <div class="sReports-container">

    <!-- REPORT CARD -->
    <div class="card sReports-card" id="notesSection">

      <h3 class="sReports-card-title">
        <i class="fa fa-notes-medical"></i> Session Report
      </h3>

      <p class="sReports-card-desc">
        This section contains guidance and recommendations provided by your counselor.
      </p>

      <div class="sReports-notesBox" id="notesContent">
        No notes available yet.
      </div>

      <button class="sReports-exportBtn" onclick="exportNotesPDF()">
        <i class="fa fa-file-pdf"></i> Export Report
      </button>

    </div>

    <!-- CURRENT TICKET -->
    <div class="card sReports-card">

      <h3 class="sReports-card-title">
        <i class="fa fa-ticket"></i> Your Session Ticket
      </h3>

      <p class="sReports-card-desc">
        This ticket is generated by your counselor/admin.
      </p>

      <div class="sReports-status">
        <b>Status:</b>
        <span id="status">Waiting for generation...</span>
      </div>

      <div class="sReports-ticket-section">
        <p><b>Ticket ID:</b></p>
        <div id="ticket" class="sReports-ticket-box">---</div>
      </div>

    </div>

    <!-- HISTORY -->
    <div class="card sReports-card">

      <h3 class="sReports-card-title">
        <i class="fa fa-clock"></i> Ticket History
      </h3>

      <p class="sReports-card-desc">
        View all previously generated tickets.
      </p>

      <p>Total Tickets: <span id="ticketCount">0</span></p>
      <ul id="ticketList" class="sReports-history-list"></ul>

    </div>

  </div>

</main>

<script>
function toggleSettingsMenu(e){
  e.stopPropagation();
  document.getElementById("settingsDropdown").classList.toggle("show");
}

function toggleTheme(){
  const html = document.documentElement;
  html.setAttribute(
    "data-theme",
    html.getAttribute("data-theme") === "light" ? "dark" : "light"
  );
}

function logout() {
  document.getElementById('logoutOverlay').classList.add('show');
}
function closeLogout() {
  document.getElementById('logoutOverlay').classList.remove('show');
}
function confirmLogout() {
    window.location.href = 'logout.php?role=student';
}

// Close when clicking outside
document.getElementById('logoutOverlay').addEventListener('click', function(e) {
  if (e.target === this) closeLogout();
});

/* CLOSE DROPDOWN */
document.addEventListener("click", e => {
  const menu = document.getElementById("settingsDropdown");
  const btn = document.querySelector(".sidebar-settingsButton");

  if (!menu.contains(e.target) && !btn.contains(e.target)) {
    menu.classList.remove("show");
  }
});

/* EXPORT REPORT */
function exportNotesPDF() {
  const element = document.getElementById("notesSection");

  const opt = {
    margin: 10,
    filename: 'Session_Report.pdf',
    image: { type: 'jpeg', quality: 1 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4' }
  };

  html2pdf().set(opt).from(element).save();
}

/* LOAD TICKETS */
function updateTicketUI() {
  let appointments = JSON.parse(localStorage.getItem("appointments")) || [];

  const approved = appointments.filter(a => a.status === "approved");

  document.getElementById("ticketCount").innerText = approved.length;

  const list = document.getElementById("ticketList");
  list.innerHTML = "";

  if (approved.length > 0) {
    const latest = approved[approved.length - 1];
    document.getElementById("ticket").innerText = latest.id;
    document.getElementById("status").innerText = latest.status;
  } else {
    document.getElementById("ticket").innerText = "---";
    document.getElementById("status").innerText = "Waiting for approval...";
  }

  approved.forEach(t => {
    const li = document.createElement("li");
    li.innerText = `${t.id} • ${t.status} • ${t.date} • ${t.time}`;
    list.appendChild(li);
  });
}
</script>
<!-- LOGOUT MODAL -->
  <div class="logout-overlay" id="logoutOverlay">
    <div class="logout-modal">
      <div class="logout-icon">
        <i class="fa fa-right-from-bracket"></i>
      </div>
      <h3>Logout</h3>
      <p>Are you sure you want to logout?</p>
      <div class="logout-actions">
        <button class="logout-btn logout-btn--cancel" onclick="closeLogout()">Cancel</button>
        <button class="logout-btn logout-btn--confirm" onclick="confirmLogout()">Yes, Logout</button>
      </div>
    </div>
  </div>

</body>
</html>