<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>UNITYCARE | Session Reports</title>

<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="sReports.css">

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">

<!-- EXPORT LIB -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
</head>

<body class="body">

<!-- SIDEBAR -->
<aside class="sidebar">
  <div class="sidebar-logoBar">
    <div class="sidebar-logo">
      <img src="logo.png" alt="logo">
      <span class="sidebar-logoText">UNITYCARE</span>
    </div>

    <div class="sidebar-settings">
      <button class="sidebar-settingsButton" onclick="toggleSettingsMenu(event)">
        <i class="fa fa-gear"></i>
      </button>

      <div class="sidebar-settingsDropdown" id="settingsDropdown">
        <a href="profile.html"><i class="fa fa-user"></i> Profile</a>
        <a href="history.html"><i class="fa fa-clock"></i> Session History</a>
        <button onclick="toggleTheme()"><i class="fa fa-moon"></i> Theme</button>
        <button onclick="logout()"><i class="fa fa-right-from-bracket"></i> Logout</button>
      </div>
    </div>

  </div>

  <nav class="sidebar-menu">
    <a href="dashboard.php"><i class="fa fa-gauge"></i> Dashboard</a>

    <p class="sidebar-title">SERVICES</p>
    <a href="booking.html"><i class="fa fa-calendar"></i> Book Appointment</a>
    <a href="sconcerns.html"><i class="fa fa-headset"></i> Submit Concern</a>
    <a href="wellness.html"><i class="fa fa-heart"></i> Wellness Check</a>
    <a href="referral.html"><i class="fa fa-route"></i> Referral</a>

    <p class="sidebar-title">UPDATES</p>
    <a href="announcements.html"><i class="fa fa-bullhorn"></i> Announcements</a>

    <p class="sidebar-title">RECORDS</p>
    <a href="sreports.php" class="active"><i class="fa fa-ticket"></i> Reports</a>

    <p class="sidebar-title">SYSTEM</p>
    <a href="feedback.html"><i class="fa fa-comment"></i> Session Feedback</a>
  </nav>
</aside>

<!-- TOPBAR -->
<header class="topbar">

  <div class="topbar-left">
    <h1>Reports</h1>
  </div>

  <div class="topbar-right">

    <div class="topbar-user">
      <img src="student.jpg" alt="user">
      <div>
        <strong>Vincent Aldolf Sablay</strong>
        <p>vincentsablay@gmail.com</p>
      </div>
    </div>

  </div>

</header>

<!-- MAIN -->
<main class="sReports-main">

  <div class="sReports-container">

    <!-- REPORT CARD -->
    <div class="card sReports-card" id="notesSection">

      <h3 class="sReports-card-title">
        <i class="fa fa-notes-medical"></i> Session Report
      </h3>

      <p class="sReports-card-desc">
        This section contains guidance and recommendations provided by your counselor.
      </p>

      <div class="sReports-notesBox" id="notesContent">
        No notes available yet.
      </div>

      <button class="sReports-exportBtn" onclick="exportNotesPDF()">
        <i class="fa fa-file-pdf"></i> Export Report
      </button>

    </div>

    <!-- CURRENT TICKET -->
    <div class="card sReports-card">

      <h3 class="sReports-card-title">
        <i class="fa fa-ticket"></i> Your Session Ticket
      </h3>

      <p class="sReports-card-desc">
        This ticket is generated by your counselor/admin.
      </p>

      <div class="sReports-status">
        <b>Status:</b>
        <span id="status">Waiting for generation...</span>
      </div>

      <div class="sReports-ticket-section">
        <p><b>Ticket ID:</b></p>
        <div id="ticket" class="sReports-ticket-box">---</div>
      </div>

    </div>

    <!-- HISTORY -->
    <div class="card sReports-card">

      <h3 class="sReports-card-title">
        <i class="fa fa-clock"></i> Ticket History
      </h3>

      <p class="sReports-card-desc">
        View all previously generated tickets.
      </p>

      <p>Total Tickets: <span id="ticketCount">0</span></p>
      <ul id="ticketList" class="sReports-history-list"></ul>

    </div>

  </div>

</main>

<script>
function toggleSettingsMenu(e){
  e.stopPropagation();
  document.getElementById("settingsDropdown").classList.toggle("show");
}

function toggleTheme(){
  const html = document.documentElement;
  html.setAttribute(
    "data-theme",
    html.getAttribute("data-theme") === "light" ? "dark" : "light"
  );
}

function logout(){
  localStorage.clear();
  window.location.href = "login.html";
}

/* CLOSE DROPDOWN */
document.addEventListener("click", e => {
  const menu = document.getElementById("settingsDropdown");
  const btn = document.querySelector(".sidebar-settingsButton");

  if (!menu.contains(e.target) && !btn.contains(e.target)) {
    menu.classList.remove("show");
  }
});

/* EXPORT REPORT */
function exportNotesPDF() {
  const element = document.getElementById("notesSection");

  const opt = {
    margin: 10,
    filename: 'Session_Report.pdf',
    image: { type: 'jpeg', quality: 1 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4' }
  };

  html2pdf().set(opt).from(element).save();
}

/* LOAD TICKETS */
function updateTicketUI() {
  let appointments = JSON.parse(localStorage.getItem("appointments")) || [];

  const approved = appointments.filter(a => a.status === "approved");

  document.getElementById("ticketCount").innerText = approved.length;

  const list = document.getElementById("ticketList");
  list.innerHTML = "";

  if (approved.length > 0) {
    const latest = approved[approved.length - 1];
    document.getElementById("ticket").innerText = latest.id;
    document.getElementById("status").innerText = latest.status;
  } else {
    document.getElementById("ticket").innerText = "---";
    document.getElementById("status").innerText = "Waiting for approval...";
  }

  approved.forEach(t => {
    const li = document.createElement("li");
    li.innerText = `${t.id} • ${t.status} • ${t.date} • ${t.time}`;
    list.appendChild(li);
  });
}
</script>

</body>
</html>